# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CI Angular app through Github Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Setup
      run: npm ci
      working-directory: frontend
    - name: Test
      run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      working-directory: frontend
    - name: Deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run deploy --if-present
      working-directory: frontend
