name: CI Angular app through Github Actions

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test & Export code coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Setup
        run: npm ci
        working-directory: frontend
      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        working-directory: frontend
      - uses: actions/upload-artifact@v3
        with:
          name: angular-coverage-node-${{ matrix.node-version }}
          path: frontend/coverage
  deploy:
    name: Build & Deploy to GitHub pages
    if: github.event_name != 'pull_request'
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Setup
        run: npm ci
        working-directory: frontend
      - name: Deploy
        if: github.event_name != 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run deploy --if-present
        working-directory: frontend
